spring:
  profiles:
    active: dev
---
# 开发环境配置
spring:
  profiles: dev
  mqtt:
    broker:
      # broker唯一标识
      id: mqtt-broker-1
      # SSL端口
      ssl-port: 8885
      # SSL密钥文件密码
      ssl-password: 123456
      # websocket端口
      websocket-ssl-port: 9995
      # websocket path 值
      websocket-path: /mqtt
      # 心跳时间(秒)
      keep-alive: 60
      # 开启Epoll模式, linux下建议开启
      use-epoll: false
      # 开启组播方式集群
      enable-multicast-group: true
      # 组播地址
      multicast-group: 239.255.255.255
      cache:
        # 持久化缓存内存初始化大小(MB)
        persistence-initial-size: 64
        # 持久化缓存占用内存最大值(MB)
        persistence-max-size: 128
        # 非持久化缓存内存初始化大小(MB)
        not-persistence-initial-size: 64
        # 非持久化缓存占用内存最大值(MB)
        not-persistence-max-size: 128
logging:
  level:
    root: info
    cn.recallcode.iot.mqtt.server: debug
---
# 生产环境
spring:
  profiles: prod
  mqtt:
    broker:
      id: mqtt-broker-1
      ssl-password: 123456
      use-epoll: true
      enable-multicast-group: false
      # 静态IP方式集群
      static-ip-addresses: 192.168.1.240, 192.168.1.241
      cache:
        persistence-initial-size: 64
        persistence-max-size: 128
        not-persistence-initial-size: 64
        not-persistence-max-size: 128
        # 持久化磁盘存储路径
        persistence-store-path: /opt/mqtt-broker/persistence
logging:
  level:
    root: warn
    cn.recallcode.iot.mqtt.server: info